---
- name: Install Lighthouse globally
  become: true
  ansible.builtin.command: "npm install -g lighthouse"
  changed_when: false
  register: lighthouse_install
  failed_when: lighthouse_install.rc != 0

- name: Check Lighthouse installation version
  become: true
  ansible.builtin.command: "/usr/local/bin/lighthouse --version"
  changed_when: false
  register: lighthouse_version
  failed_when: lighthouse_version.rc != 0

- name: Print Lighthouse version
  ansible.builtin.debug:
    msg: "Lighthouse version: {{ lighthouse_version.stdout }}"

- name: Lighthouse | create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouseconf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
